-- @description KW Script Bundle
-- @version 1.2
-- @changelog
--  + Added better user support
-- @author Carlos Wunsche
-- @metapackage
-- @provides
--  [nomain] .
--  [nomain] KW_User.lua
--  [main=main] KW_Reaper startup.lua
--  [main=main] KW_Play-stop.lua
-- @about
--    # Description
--    * My personal script bundle.
-- @link Github https://github.com/carloswunsche/