-- @description KW Script Bundle
-- @version 1.1
-- @changelog
--  + Better User Support
-- @author Carlos Wunsche
-- @metapackage
-- @provides
--  [main=main] KW_Reaper startup.lua
--  [main=main] KW_Play-stop.lua
-- @about
--    # Description
--    ## My personal script bundle.
--    ### Under construction...
-- @link Github https://github.com/carloswunsche/
